apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ahtq9vjmm-dotnet-basic
  janus-idp.io/tekton: ahtq9vjmm-dotnet-basic
  backstage.io/kubernetes-id: ahtq9vjmm-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ahtq9vjmm-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
